main: me.spikey.newplayercommand.Main

name: AutoQueuePlugin
version: 1.0
api-version: 1.13
author: SpikeyNoob, PhoenixZT

commands:
  removeautoqueue:
    permission: autoqueue.staff
    aliases:
  #    - removeautorequeue
  #    - removeautojoin
  autoqueue:
    permission: autoqueue.command
    aliases:
  #    - autorequeue
  #    - autojoin